[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
board_build.usb_type = USB_SERIAL
monitor_speed = 115200
upload_protocol = teensy-cli
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/vjmuzik/NativeEthernet
    https://github.com/vjmuzik/FNET
board_microros_distro = humble
board_microros_transport = custom
