[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
board_microros_transport = custom
board_microros_distro = humble
upload_protocol = teensy-cli
lib_deps = 
    https://github.com/vjmuzik/FNET.git
    https://github.com/vjmuzik/NativeEthernet.git
    https://github.com/micro-ROS/micro_ros_platformio.git#main
    teemuatlut/TMCStepper@^0.7.3
